name:
  _target_: improved_diffusion.tasks.DeclippingTask




metrics:
  wv-mos:
    _target_: improved_diffusion.MOSNet
    weights_path: weights/wave2vec2mos.pth
    pretrained_path: weights/fb_w2v2_pretrained
    sr: 16000
    num_splits: 4
    device: cuda
  sisnr:
    _target_: improved_diffusion.SiSNR
