defaults:
  - task: declipping
  - model: diffwave
  - diffusion: gaussian_diffusion
  - _self_

output_dir: results/declipping_inference
audio_dir: /home/public_datasets/VCTK-Corpus-0.92/wav48_silence_trimmed/p254
use_ema: false
segment_size: 72000
sampling_rate: 16000
device: cuda